### ISSUE TITLE
how to run this project

### ISSUE THREAD

**Issue by shubhamgithub1** [chenzlabs/aframe-ar-plane#16]
i'm trying to run your various project which seemed wonderful but i'm unable to run it.
please can you tell me steps to run this projects

**Comment by machenmusik** [comment]
Sorry about the terse README, there is a little more information at the main repo at https://github.com/chenzlabs/aframe-ar

This was built for an earlier time where only experimental browsers supported web-based AR, such as Mozilla's WebXR Viewer for iOS, and Google's experimental WebAR browsers for iOS and Android.  Since then, Google has added some support into mobile Chrome on Android, but the most recent version has broken that again unfortunately.  Once the smoke clears, I hope to support that as well, see https://github.com/chenzlabs/aframe-ar/issues/40
